name: Trigger auto deployment for container-app-fgp7xfkuycmno

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-fgp7xfkuycmno-AutoDeployTrigger-59e115d8-0830-4fd8-83c0-8214a937aa78.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPFGP7XFKUYCMNO_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPFGP7XFKUYCMNO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPFGP7XFKUYCMNO_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPFGP7XFKUYCMNO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPFGP7XFKUYCMNO_REGISTRY_PASSWORD }}
          containerAppName: container-app-fgp7xfkuycmno
          resourceGroup: demoazure9864
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


